
services:
  api:
    container_name: nestjs01
    image: node:20.18.0
    working_dir: /app/api
    env_file:
      - .env
    volumes:
      - "./api:/app/api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: [ "npm", "run", "start:dev"]

  web:
    container_name: ${PROJECT_NAME}-web
    image: node:20.18.0
    working_dir: /app/web
    env_file:
      - .env
    volumes:
      - './web:/app/web'
    ports:
      - '4000:3000'
    command: ['npm','run','dev']


  db:
    container_name: f8-k7-full-project
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '4000:5432'
    volumes:
      - './db:/var/lib/postgresql/data'
volumes:
  db:
    driver: local